# config.yaml
# Stores global configuration settings for the framework

browser: chrome               # Options: chrome, firefox, edge
base_url: "https://staging.example.com"  
timeout: 10                   # Default wait time for elements (in seconds)

# Reporting
report_path: "reports/"
screenshot_path: "screenshots/"
log_path: "logs/"

# Logging
log_level: INFO               # Options: DEBUG, INFO, WARNING, ERROR

# Credentials (for demo only — in real use, store in .env instead)
username: "testuser"
password: "password123"
